[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200

; Configuração física da tua Flash de 8MB
board_build.flash_size = 4MB
board_upload.flash_size = 4MB

; Ativa a tabela Huge App (No OTA) que expande o limite do código para 3.1MB
board_build.partitions = huge_app.csv

lib_deps =
    electroniccats/MPU6050 @ 1.4.4
    bblanchon/ArduinoJson @ 7.4.3